[build]
  command = "npm run build"
  publish = "dist" # Correct build output directory for Vite

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' https://*.supabase.co https://rifolks-drifts.railway.app; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://*.supabase.co; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.supabase.co https://rifolks-drifts.railway.app;" # Updated backend URL

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  # package = "@netlify/plugin-nextjs" # Removed incorrect plugin for Vite

# Removed redundant API proxy redirect as frontend calls API directly
# [[redirects]]
#   from = "/api/*"
#   to = "https://rifolks-drifts-production.up.railway.app/api/:splat"
#   status = 200
#   force = true