[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci --omit=dev && npx prisma generate"
watchPatterns = ["/backend/**/*"]

[deploy]
startCommand = "cd backend && NODE_ENV=production npm run migrate && PORT=$PORT npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
startupTimeout = 180

[deploy.envVars]
NODE_ENV = "production"
PORT = "3001"
SUPABASE_URL = "https://asopomvrogpnirgguquy.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzb3BvbXZyb2dwbmlyZ2d1cXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzE4OTksImV4cCI6MjA1ODkwNzg5OX0.GZifjJopG_Sd3e_4XKtpVH-qPkAeqQeRe_7x5Mn9-rI"
DATABASE_URL = "postgresql://postgres.asopomvrogpnirgguquy:z3v6hUVJMMfZtC5v@aws-0-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
DIRECT_URL = "postgresql://postgres.asopomvrogpnirgguquy:z3v6hUVJMMfZtC5v@aws-0-ap-south-1.pooler.supabase.com:5432/postgres"
ALLOWED_ORIGINS = "https://rifolks-drifts.netlify.app,http://localhost:3000"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"
LOG_LEVEL = "info"
DATABASE_CONNECTION_RETRIES = "5"
DATABASE_CONNECTION_RETRY_DELAY = "5000"
PRISMA_CLIENT_ENGINE_TYPE = "dataproxy" 