[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci --omit=dev && npx prisma generate"
watchPatterns = ["/backend/**/*"]

[deploy]
startCommand = "cd backend && npm run migrate && NODE_ENV=production PORT=$PORT npm start"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckInterval = 30
startupTimeout = 600

[deploy.envVars]
NODE_ENV = "production"
PORT = "3001"
SUPABASE_URL = "https://asopomvrogpnirgguquy.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzb3BvbXZyb2dwbmlyZ2d1cXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzE4OTksImV4cCI6MjA1ODkwNzg5OX0.GZifjJopG_Sd3e_4XKtpVH-qPkAeqQeRe_7x5Mn9-rI"
DATABASE_URL = "postgresql://postgres.asopomvrogpnirgguquy:z3v6hUVJMMfZtC5v@aws-0-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=1"
DIRECT_URL = "postgresql://postgres.asopomvrogpnirgguquy:z3v6hUVJMMfZtC5v@aws-0-ap-south-1.pooler.supabase.com:6543/postgres"
ALLOWED_ORIGINS = "https://rifolks-drifts.netlify.app,http://localhost:3000"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"
LOG_LEVEL = "info"

[deploy.healthcheck]
interval = "30s"
timeout = "600s"
retries = 3
startPeriod = "60s" 