[build]
builder = "nixpacks"
buildCommand = "npm install && npm run prisma:generate"

[deploy]
startCommand = "npm run prisma:migrate && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"

[deploy.checks]
database = { type = "postgresql" } 